__init__.py
from flask import Flask
from views import main
import os

global app
debug = True


app = Flask(__name__)

app.register_blueprint(main)

app.config['SECRET_KEY'] = "CS205secretkey"

#Local host

# if __name__ == "__main__":
# 	app.run(debug=debug, host = '127.0.0.1')

# AWS 
if __name__ == "__main__":

	app.run(host='0.0.0.0',port='80')

app.py
from flask import Flask
def create_app():
    # create app object
    app = Flask(__name__)
    # register the Blueprint by importing and registering 
    from views import main
    app.register_blueprint(main)

    return app

auth.py
# Authorization for user signing up or logging in/out of our server
import gc
import wrap

from flask import Blueprint, request, redirect, url_for, render_template, flash, session
from . import db
from backEnd import BackEndInterface
from flask_login import LoginManager, login_user, logout_user, current_user
from flask import current_app as app

# Connect to server
serverInterface = BackEndInterface("205final")
serverInterface.connectToServer()

@app.route("/main_login/", methods = ["GET", "POST"])
def login():
    error = ""
    # Bypass if user is already logged in
    if current_user.is_authenticated:
        return redirect(url_for('home.html'))
    try:
        if request.method == "POST":
            # Get attempted email and password
            attempted_email = request.form.get('Email')
            attempted_password = request.form.get("password")
            # Attempt to find user with this email
            # Will return true if user is verified
            # use email because it is unique to every user
            if serverInterface.verifyUser(attempted_email, attempted_password):
                # Define a new session variable
                session['logged_in'] = True
                session['username'] = request.form.get('username')
                flash("You are now logged in")
                next_page = request.args.get('next')
                # Redirect user
                # user has correct credentials
                return redirect(url_for("main.home"))

            else:
                error = "Invalid Credentials. Try Again"
                return redirect(url_for("main.home_login", error=error))

        return redirect(url_for("main.home_login", error = error))

    except Exception as e:
        flash(e)
        return redirect(url_for("main.home_login.html", error=error))


@app.route('/sign', methods = ["GET", "POST"])
def signup():
    error = ""
    try:
        if request.method == 'POST':
            email = request.form.get('email')
            username = request.form.get('username')
            password = request.form.get('password')

            # Check if user already exists in database
            if serverInterface.signUser(email, username, password):
                # User has been created, now we want to redirect to login page
                return redirect(url_for('main_login.html'))

            else:
                # User already exists
                flash("Email already exists. Try logging in or make another account")
                redirect(url_for('main.sign'))

        redirect(url_for("main.sign"))

    except Exception as e:
        print(e)
    return render_template("sign.html")

def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            flash("You must log in first")
            return redirect(url_for("main.home_login"))

@app.route('/logout')
@login_required
def logout():
    session.clear()
    flash("You have been logged out")
    gc.collect()
    return redirect(url_for("main.home"))


@login_manager.user_loader
def load_user(user_id):
    """Checks if user is logged-in on every page load."""
    if user_id is not None:
        return getUsername(email)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('main.home_login'))

routes.py
from flask import Blueprint, render_template, redirect
from flask_login import current_user, login_required
from flask import current_app as app
from .assets import compile_auth_assets


# Configure blueprint
main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
compile_auth_assets(app)

@main_bp.route('/', methods = ['GET'])
@login_required
def dashboard():
    return render_template('home.html',
                           template = 'home.html',
                           current_user = current_user)

views.py
import os

from flask import Blueprint, render_template, request, redirect, url_for, send_from_directory, current_app, flash, send_file

from werkzeug.utils import secure_filename


from backEnd2 import BackEndInterface

serverInterface = BackEndInterface("205final")
# serverInterface.connectToServer()

# create the first grouping for the blueprint

main = Blueprint("main",
                    __name__,
                    template_folder="templates",
                    static_folder="static",
                    static_url_path="/static"
                    )

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

@main.route('/')
def home():

	assetList = serverInterface.selectXfromAssets(5)
	#assetList = [("id","fileName","fileLocation","fileDescription","fileImage")]
	return render_template('home.html', assetList=assetList)

@main.route('/download-file2/<folder>/<name>', methods=['GET'])
def home_download(folder,name):

	path = os.getcwd()
	
	
	
	print("\n\n" + str(name)+"\n\n")
	
	
	return send_file(str(folder)  + "/" + str(name),
					attachment_filename=str(name),
					as_attachment=True)


@main.route('/', methods=['POST'])
def home_login():
	email = request.form.get('email')
	password = request.form.get('password')
	return render_template('fileTransfer.html')


@main.route('/about')
def about():
	return render_template('about.html')


@main.route('/sign')
def sign():
	return render_template('sign.html')

@main.route('/contact')
def contact():
	return render_template('contact.html')

@main.route('/contact', methods=['POST'])
def contact_post():
	email = request.form.get('email')
	subject = request.form.get('subject')
	messageContent = request.form.get('messageContent')

	# function call - give that to backend
	return redirect(url_for('main.home')) #Example redirect 



@main.route('/sign', methods=['POST'])
def sign_post():
	error = ""
	print("SIGNUP FUNCTION EXECUTED\n")

	try:
		if request.method == 'POST':
			email = request.form.get('email')
			username = request.form.get('username')
			password = request.form.get('psswrd')
			rpassword = request.form.get('repeatpsswrd')

			if rpassword != password:
				flash("Passwords don't match")
				return redirect(url_for('main.sign'))

			# DEBUGGING
			print(str(email) + '\n' + str(username) + '\n' + str(password) + '\n')
           		 # Check if user already exists in database
			if serverInterface.signUser(str(username), str(password), str(email)):
                       # User has been created, now we want to redirect to login page
				return redirect(url_for('main.home_login'))

			else:
                # User already exists
				print("Views.py: User exists, redirecting to main.sign")
				redirect(url_for('main.sign'))

		redirect(url_for("main.sign"))

	except Exception as e:
		print(e)

	return render_template("sign.html")

@main.route('/fileTransfer')
def fileTransfer():
	return render_template('fileTransfer.html')
#    return f"Email: {email} Password: {password}"


# Define function that checks if a file is allowed to be uploaded
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS




@main.route('/upload-file', methods =['POST'])
def upload_file():
	print('\n\nROUTE HIT \n\n')
	
	f = request.files['filename']
	fileDescr = request.form.get('fileDescription')

	print('\n\n' + str(f.filename) + '\n\n' + str(fileDescr) + '\n\n')

	path = os.path.join(current_app.root_path,'static/')

	f.save(os.path.join(path,secure_filename(f.filename)))

	serverInterface.createRowAssetTable(f.filename,fileDescr)

	return 'file uploaded succesfully'

templates/about.html
<!-- This page needs to be updated to an "about us" page for the group -->
{% extends 'base.html' %}
{% block title %}Open Software{% endblock %}
{% block css %}
<link , href="{{url_for('static', filename='css/blog.css') }}" rel="stylesheet">
<html lang="en">
{% endblock %}


{% block body %}
<div class="container-fluid theme-showcase" role="main" style="max-width: 75%">
    <div class="jumbotron text-center" style="background-color: transparent; color: white">
        <h1>About Us</h1>
        <!-- May move this description elsewhere -->
        <p style="color: white"> Meet the team
        <p>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <h2 style="color: white">Matthew Piatt</h2>
                <h5 style="color: white"> ENTRY DESCRIPTION</h5>
                <!-- Add image here -->
                <img class="img-responsive" style="height: 250px; margin-right: 20px"

                src="{{url_for('static', filename='MattP.jpg') }}"

                align="left">

                <p style="color: white"> Did you ever hear the tragedy of Darth Plagueis The Wise? I thought not. It’s
                    not a story the Jedi would tell you. It’s a Sith legend. Darth Plagueis was a Dark Lord of the Sith,
                    so powerful and so wise he could use the Force to influence the midichlorians to create life… He had
                    such a knowledge of the dark side that he could even keep the ones he cared about from dying. The
                    dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so
                    powerful… the only thing he was afraid of was losing his power, which eventually, of course, he did.
                    Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his
                    sleep. Ironic. He could save others from death, but not himself. </p>

            </div>




            <div class="card">
                <h2 style="color: white">Mario Vega</h2>
                <h5 style="color: white"> ENTRY DESCRIPTION</h5>
                <!-- Add image here -->
                
                <img class="img-responsive" style =" height: 250px; margin-right: 20px;"

                src="{{url_for('static', filename='MarioV.jpeg') }}"

                align="left" alt="Picture of Mario Vega">

                <p style="color: white"> Did you ever hear the tragedy of Darth Plagueis The Wise? I thought not. It’s
                    not a story the Jedi would tell you. It’s a Sith legend. Darth Plagueis was a Dark Lord of the Sith,
                    so powerful and so wise he could use the Force to influence the midichlorians to create life… He had
                    such a knowledge of the dark side that he could even keep the ones he cared about from dying. The
                    dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so
                    powerful… the only thing he was afraid of was losing his power, which eventually, of course, he did.
                    Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his
                    sleep. Ironic. He could save others from death, but not himself. </p>
            </div>

        </div>

        <div class="col-md-6">
            <div class="card">
                <h2 style="color: white">Matthew Halligan</h2>
                <h5 style="color: white"> ENTRY DESCRIPTION</h5>
                <!-- Add image here -->
                <img class="img-responsive" style="height: 250px; max-width: 250px; margin-right: 20px;" 

                src="{{url_for('static', filename='MattH.jpeg') }}"

                align="left" alt="Picture of Matt H">

                <p style="color: white"> Did you ever hear the tragedy of Darth Plagueis The Wise? I thought not. It’s
                    not a story the Jedi would tell you. It’s a Sith legend. Darth Plagueis was a Dark Lord of the Sith,
                    so powerful and so wise he could use the Force to influence the midichlorians to create life… He had
                    such a knowledge of the dark side that he could even keep the ones he cared about from dying. The
                    dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so
                    powerful… the only thing he was afraid of was losing his power, which eventually, of course, he did.
                    Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his
                    sleep. Ironic. He could save others from death, but not himself. </p>
            </div>

            <br>

            <div class="card">
                <h2 style="color: white">Ben Caruso</h2>
                <h5 style="color: white"> ENTRY DESCRIPTION</h5>
                <!-- Add image here -->
                <img class="img-responsive" style="height: 250px; margin-right: 20px" 

                src="{{url_for('static', filename='Ben.jpg') }}" 

                alt="Picture of Ben" align= "left">
                <p style="color: white"> Did you ever hear the tragedy of Darth Plagueis The Wise? I thought not. It’s
                    not a story the Jedi would tell you. It’s a Sith legend. Darth Plagueis was a Dark Lord of the Sith,
                    so powerful and so wise he could use the Force to influence the midichlorians to create life… He had
                    such a knowledge of the dark side that he could even keep the ones he cared about from dying. The
                    dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so
                    powerful… the only thing he was afraid of was losing his power, which eventually, of course, he did.
                    Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his
                    sleep. Ironic. He could save others from death, but not himself. </p>
            </div>

        </div>
    </div>
    {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta CONTENT="IE=EDGE" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">

    <title>{% block title %}{% endblock %}</title>

    <link , href="{{url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link , href="{{url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">
    {% block css %}{% endblock %}




    <nav class ="navbar navbar-inverse navbar-fixed-top" data-spy="affix" data-offset-top="197">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">OpenSource Repo </a>
            </div>

            <ul class="nav navbar-nav navbar-right" >
                <li class=""><a id="homeLink" onclick="home_click" href="/">Home</a></li>
                  <!-- Redirect to the home page if the home button is pressed --javascript- -->
                    <!-- pages to be linked later -->
                <li><a class="blog" onclick="blog_click" href="{{url_for('main.about') }}">About </a></li>
                <li><a href="{{url_for('main.contact') }}">Contact Us </a></li>
                <li><a href="{{url_for('main.sign') }}">Sign up </a></li>
            </ul>

    </nav>

</head>


<style>
    body{
        background-image: linear-gradient(to right, red 0%, blue 50%), url('https://i.pinimg.com/originals/bb/61/8d/bb618db7d825e2e03c8d86f781a65e06.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        /*position: relative;*/
        background-color: transparent;
        background-position: center;
        background-blend-mode: darken;
    }
/*<!-- To be ported to css?  -->*/
  }
  .navbar {
    margin-bottom: 0px;
    
  }

  .affix ~ .container-fluid {
   position: relative;
   top: 50px;
  }

  .footer{
    position: absolute;
  }
</style>


<body>
{% block body %}{% endblock %}
</body>
<!-- Footer -->
<footer class="page-footer-bottom" style="font:small" >
    <hr>
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="">Website name</a>
    </div>
    <!-- Copyright -->
</footer>
</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %}Open Software{% endblock %}

{% block body %}

<div class="container theme-showcase" role="main">
    <div class="jumbotron text-center" style="background-color: transparent;">
        <h1 style="color: white">Contact Us</h1>
        <p style="color: white"><b>Have a bug to report? Service not working? Login issues? Let us know below.</b></p>
    </div>
</div>

<hr>

<div row>

	<div class ="col-md-8 col-md-offset-2" align="center">
		<div class ="panel panel-info" style="max-width: 75%">
			<div class ="panel-body" align="center">
				<form method="POST" action="/contact">
					<div class="form-group row text-center" style="max-width: 75%;">
						<label for="Email" class="col-sm-12 col-form-label">Email</label>
						<div class="form-group">
							<input type="text" id="Email" class="form-control" placeholder="you@example.com" name="email" required>
						</div>
					</div>

					<div class="form-group row text-center" style="max-width: 75%;">
						<label for="topic" class ="col-sm-12 col-form-label">Subject</label>
						<div class="form-group">
							<input type="text" id="Subject" class="form-control" name="subject" required>
						</div>
					</div>

					<div class="form-group row text-center" style="max-width: 75%;">
						<label for="content" class="col-sm-12 col-form-label">How can we help?</label>
						<div class="form-group">
							<textarea type="text" id="Content" class="form-control" rows="5" name="messageContent" required> </textarea>
						</div>
					</div>

					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>

		</div>
	</div>
<!-- This is fake space to move content down, otherwise footer is not pushed to bottom of page -->
<!-- Alternate solution to be implemented? -->
	<div row>
		<br><br><br><br>
		<br><br><br><br>
		<br><br><br><br>
		<br><br><br><br>
		<br><br><br><br>
		<br><br><br><br>
	</div>

</div>
{% endblock %}

templates/fileTransfer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta CONTENT="IE=EDGE" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">

    <title>OpenSource</title>

    <link , href="{{url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link , href="{{url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">   




    <nav class ="navbar navbar-inverse navbar-fixed-top" data-spy="affix" data-offset-top="197">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">OpenSource Repo </a>
            </div>

			<div>
				<ul class="nav navbar-nav navbar-right" >
					<li class=""><a id="homeLink" onclick="home_click" href="/">Home</a></li>
					<!-- Redirect to the home page if the home button is pressed --javascript- -->
					<!-- pages to be linked later -->
					<li><a class="blog" onclick="blog_click" href="{{url_for('main.about') }}">About </a></li>
					<li><a href="{{url_for('main.contact') }}">Contact Us </a></li>

					<li><a href="{{ url_for('main.home') }}">Sign out</a></li>

				</ul>
			</div>

    </nav>

</head>

<style>
    body{
        background-image: linear-gradient(to right, red 0%, blue 50%), url('https://i.pinimg.com/originals/bb/61/8d/bb618db7d825e2e03c8d86f781a65e06.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        /*position: relative;*/
        background-color: transparent;
        background-position: center;
        background-blend-mode: darken;
    }
/*<!-- To be ported to css?  -->*/
  }
  .navbar {
    margin-bottom: 0px;
    
  }

  .affix ~ .container-fluid {
   position: relative;
   top: 50px;
  }

  .footer{
    position: absolute;
  }
</style>

<body>

<div class ="container theme-showcase" role="main">
	<div class ="jumbotron text-center" style="background-color: transparent;">
		<h1 style="color: white">Upload File</h1>
		<p style="color: white"><b></b></p>
	</div>
</div>

<br><br><br><br>

<div row>
	<div class="col-md-6 col-md-offset-3">
		<h2 style="font:bold; color:white" align="center">Select File to Upload</h2>
		<hr>

		<div class ="col-md-offset-2">
			<div class ="panel panel-default" style ="width:75%">

				<form action= "/upload-file" method = "POST" enctype = "multipart/form-data">
					<div class ="panel-body text-center" style="">
							<input type="file" id="myfile" name="filename">
							<br>
							<textarea type="text" id="description" name="fileDescription" rows = 10 placeholder="fileDescription" style="float: left"></textarea>

							<img src="http://icons.iconarchive.com/icons/icojam/blue-bits/256/document-arrow-up-icon.png" style ="height: 150px; width: 150px float: right" class ="img-rounded">
							
					</div>

				<div class ="panel-footer">
					<input type="submit" style="float: right">
					<br>
				</div>

				</form>

			</div>
		</div>
	</div>


</div>

<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>

<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>


</body>


<!-- Footer -->
<footer class="page-footer-bottom" style="font:small" >
    <hr>
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="">Website name</a>
    </div>
    <!-- Copyright -->
</footer>



</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Open Software{% endblock %}

{%block css%}
<link href="{{url_for('static', filename='css/home.css') }}", rel="stylesheet">

{% endblock %}

{% block body %}
		

<div class ="container-fluid theme-showcase" role="main" style="max-width: 85%" >
	<div class ="jumbotron text-center" style="background-color: transparent;">
		<h1 style="color:white">Open Source Repository</h1>
		<!-- May move this description elsewhere -->
		<p style="color: white"> Welcome to this open source repository, where files dealing with a vairety of topics can be found. Try a search and see what information you can find. Remember to sign up in order to download anything. <p>
	</div>

<div class="container-fluid">
    <div class="row">
        <div align="left" class="col-sm-3">
            <div class="panel panel-default" style="background-blend-mode: overlay;">
                <div class="panel-heading text-center"><h3>Team OpenSource Repo</h3></div>
                <div class="panel-body">
                    <p align="left">Matthew Piatt<span style="float:right"> Ben Caruso</span></p>
                    <p align="left">Mario Vega<span style="float:right"> Matthew Halligan</span></p>
                </div>
            </div>
        </div>

        <div align="center" class="col-sm-6">
            <h3>Work in Progress</h3>
            <form class="form-inline">
                <div class="form-group">
                    <!-- Label for what the user wants to download. May need to change! -->
                    <label for="query"></label>
                    <!-- Need to know what to put for the id -->
                    <input class="form-control" id="" placeholder="Search for..." type="text">
                </div>

                <button class="btn btn-primary" type="submit">
                    <span class="glyphicon glyphicon-search"></span> Search
                </button>
            </form>
        </div>
        <div class="container-fluid">
            <div class="row">

                <form action="{{ url_for('main.home_login') }}" method="post">
                    <div align="right" class="col-sm-3">
                        <div class="panel panel-default" style="background-blend-mode: overlay;">
                            <div class="panel-heading text-center"><h3>User Login</h3></div>
                            <div class="panel-body">
                                <p align="center">
                                    <label for="email">Email:</label><br>
                                </p>
                                <p align="center">
                                    <input id="email" name="email" type="text"><br>
                                </p>
                                <p align="center">
                                    <label for="password">Password:</label><br>
                                </p>
                                <p align="center">
                                    <input id="psswrd" name="password" type="text"><br><br>
                                </p>
                                <input onclick="myFunction()" type="checkbox">Show Password
                                <script>
                                    /* Shows the password when user presses show password using java script  */
                                    function myFunction() {
                                        var x = document.getElementById("psswrd");
                                        if (x.type === "password") {
                                            x.type = "text";
                                        } else {
                                            x.type = "password";
                                        }
                                    }
                                </script>
                                <input type="submit" value="Login" >
                                <input type="submit" value="Forgot Account">

                            </div>
                        </div>
                    </div>
                </form>

				<br>
				<br>
				<hr>

			</div>

	<div class="row">

		<div class ="col-sm-9 col-sm-offset-2">
			<div class ="list-group">

				<!-- Schematic for preview/ download button. Note if user not logged in cannot download -->
				{% for asset in assetList %}
				<div style="background-color: transparent;" class="list-group-item">
					<form action="/download-file2/{{asset[2]}}" method="GET">
						<img src ="{{asset[4]}}" class="img-responsive" 
						style="float:left; max-height: 175px; padding-right: 10px" alt="File Image">
						<h2 style="color: white" align="center" name = "fileName">{{asset[1]}}</h2>
					
						<p style= "color: white;">{{asset[3]}}</p>

						
							<button id = "{{asset[0]}}" type="submit" class="btn btn-default" style="float: right;"  name="{{asset[1]}}" >Download</button>

						
					</form>

					<br>
					<br>


				</div>


				<br>
				<br>
				{% endfor %}
 
			</div>
		</div>
				
	</div>
{% endblock %}

templates/main_login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta CONTENT="IE=EDGE" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    
    <link , href="{{ url_for('static', filename='css/main_login.css') }}" rel="stylesheet">
    <link , href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link , href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">
    <title>Open Software</title>
    <nav class="navbar navbar-inverse">
        <ul class="nav navbar-nav navbar-right">
            <li class="home"><a href="{{ url_for('main.home') }}" id="homeLink">Home</a></li>
            <!-- Pages to be linked later-->
            <li><a class="blog" href="{{ url_for('main.about') }}">about</a></li>
            <li><a class='Contact' href="{{ url_for('main.contact') }}">Contact us</a></li>

            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">Account</a>
                <div class="dropdown-content">
                    <a href="{{ url_for('main.home') }}">Sign out</a>
                    <a href="{{ url_for('main.home') }}">Delete account</a>
                </div>
            </li>
        </ul>
    </nav>
</head>
<div row>
    <div class="container-fluid">
        <div class="row">
            <div align="left" class="col-sm-3">
                <div class="panel panel-default" style="background-blend-mode: overlay;">
                    <div class="panel-heading text-center"><h3 align="center">Upload File</h3></div>
                    <form action="/action_page.php">
                        <h4 align="center" style="color: #a6e1ec">Click a file for upload</h4>
                        <div style="text-align: center">
                            <input type="file" id="myFile" name="filename" style="color: #e0e0e0">
                            <input type="submit">
                        </div>
                        <br><br><br><br>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<div row>
    <div class="container-fluid">
        <div class="row">
            <div align="left" class="col-sm-3">
                <div class="panel panel-default" style="background-blend-mode: overlay;">
                    <div class="panel-heading text-center"><h3 align="center">Download File</h3></div>
                    <form action="" method="POST">
                        <h4 align="center" style="color: #a6e1ec">Click too Download</h4>
                        <div style="text-align: center">
                            <input type="file" id="myFile" name="filename" style="color: #e0e0e0">
                            <input type="submit">
                        </div>
                        <br><br><br><br>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<body>
</body>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br>
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>
</html>